"""empty message

Revision ID: 4b40fc5e3fe6
Revises: 5bd23129351f
Create Date: 2017-07-14 20:15:23.190808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b40fc5e3fe6'
down_revision = '5bd23129351f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('film', 'release',
               existing_type=sa.DATE(),
               type_=sa.Integer(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('film', 'release',
               existing_type=sa.Integer(),
               type_=sa.DATE(),
               existing_nullable=True)
    # ### end Alembic commands ###
