"""empty message

Revision ID: 5bd23129351f
Revises: 3f4ca008b497
Create Date: 2017-07-14 20:01:55.020349

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5bd23129351f'
down_revision = '3f4ca008b497'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('film', sa.Column('ratings', sa.Float(), nullable=True))
    op.alter_column('film', 'duration',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=300),
               existing_nullable=True)
    op.alter_column('film', 'quality',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               type_=sa.String(length=300),
               existing_nullable=True)
    op.alter_column('film', 'stars',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               type_=sa.String(length=300),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('film', 'stars',
               existing_type=sa.String(length=300),
               type_=postgresql.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('film', 'quality',
               existing_type=sa.String(length=300),
               type_=postgresql.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('film', 'duration',
               existing_type=sa.String(length=300),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_column('film', 'ratings')
    # ### end Alembic commands ###
